version: '3'

services:
  api:
    container_name: agent_simulation_api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "9999:9999"
    networks:
      - agent_simulation_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
#      - gama_server
#
#  gama_server:
#    container_name: agent_simulation_gama_server
#    build:
#      context: .
#      dockerfile: docker/gama_server/Dockerfile
#    ports:
#      - "6868:6868"
#    networks:
#      - agent_simulation_net

  db:
    container_name: agent_simulation_db
    image: mysql:8.4
    ports:
      - "10306:3306"
    networks:
      - agent_simulation_net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agent_simulation
      MYSQL_USER: agent_simulation_user
      MYSQL_PASSWORD: agent_simulation_password
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - agent_simulation_data_volume:/var/lib/mysql

  redis:
    container_name: agent_simulation_redis
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - agent_simulation_net

networks:
  agent_simulation_net:
    driver: bridge

volumes:
  agent_simulation_data_volume:
