services:
  api:
    container_name: ags_local_api
    build:
      context: .
      dockerfile: docker/local/api/Dockerfile
    volumes:
      - ./:/app
      - ./projects:/app/projects
      - ./gama/gama-platform:/opt/gama-platform
    ports:
      - "9999:9999"
    networks:
      - ags_network
    depends_on:
      - db
      - redis

  db:
    container_name: ags_local_db
    image: mysql:8.4
    ports:
      - "13306:3306"
    networks:
      - ags_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ags
      MYSQL_USER: agsuser
      MYSQL_PASSWORD: 123
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ags_db_volume:/var/lib/mysql

  redis:
    container_name: ags_local_redis
    image: redis:7.4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ags_redis_volume:/data/
      - ./docker/local/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "16379:6379"
    networks:
      - ags_network

networks:
  ags_network:
    driver: bridge

volumes:
  ags_db_volume:
  ags_redis_volume:
