services:
  api:
    container_name: agent_simulation_local_api
    build:
      context: .
      dockerfile: docker/local/api/Dockerfile
    volumes:
      - ./:/app
      - ./projects:/app/projects
      - ./gama/gama-platform:/opt/gama-platform
    ports:
      - "9999:9999"
    networks:
      - agent_simulation_net
    depends_on:
      - db
      - redis
  #      - gama_server
  #
  #  gama_server:
  #    container_name: agent_simulation_gama_server
  #    build:
  #      context: .
  #      dockerfile: docker/gama_server/Dockerfile
  #    ports:
  #      - "6868:6868"
  #    networks:
  #      - agent_simulation_net

  db:
    container_name: agent_simulation_local_db
    image: mysql:8.4
    ports:
      - "13306:3306"
    networks:
      - agent_simulation_net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agent_simulation
      MYSQL_USER: agsuser
      MYSQL_PASSWORD: agspassword
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - agent_simulation_data_volume:/var/lib/mysql

  redis:
    container_name: agent_simulation_local_redis
    image: redis:7.4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - agent_simulation_redis_data:/data/
      - ./docker/local/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "16379:6379"
    networks:
      - agent_simulation_net

networks:
  agent_simulation_net:
    driver: bridge

volumes:
  agent_simulation_data_volume:
  agent_simulation_redis_data:
